---
title: "ADNI EDA"
output: html_document
date: '2023-11-28'
---

## Setup

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(gamlss, gamlss.cens, gamlss.mx, gamlss.tr, ggplot2, tidyverse, ggpubr, skimr, gamlss.data, data.table, nlme, devtools, slider, see)

# #pull plotting functions from github
# plot.func.url <- "https://raw.githubusercontent.com/BGDlab/GAMLSS/main/plotting_functions.R?token=GHSAT0AAAAAACGAYP4HZWCTHACGUM6KG2PSZIQUPBA"
# Sys.setenv(GITHUB_PAT = "") #if needed to access private BGDlab GAMLSS repo
# source_url(plot.func.url) #sometimes doesn't work....?

source("/Users/megardn/Desktop/BGD_Repos/GAMLSS/plotting_functions.R")
source("/Users/megardn/Desktop/BGD_Repos/combat_biovar/R_scripts/gamlss_helper_funs.R")
```

Load data from Jakob
```{r}
adni.df <- readRDS("data/ADNIforMargaret.RDS")
#skim(adni.df)

#Lots of empty data, dropping
adni.df.filt <- adni.df %>%
  janitor::remove_empty(which = "cols")
skim(adni.df.filt)

#check for duplicate subjects
nrow(adni.df.filt) == n_unique(adni.df.filt$participant)
```

restrict to one scan per subject for visualizing demographics

```{r}
adni.df.no_dup <- adni.df.filt %>%
  arrange(age_days) %>%
  group_by(participant) %>%
  slice(1) %>%
  ungroup() %>%
  group_by(site) %>%
  filter(n() >= 2) %>%
  ungroup() #drop sites w <2 ppl

nrow(adni.df.no_dup) == n_unique(adni.df.no_dup$participant)
```

## Site-wise EDA

look for variance-effecting features that are confounded by site

### Age

```{r}
ggplot(adni.df.no_dup) +
  geom_violin(aes(x=site, y=age), scale="width", trim = FALSE, adjust=0.75)
```

```{r}
ggplot(adni.df.no_dup) +
  geom_violin(aes(x=site, y=age, fill=sex, color=sex), scale="width", trim = FALSE, adjust=0.75)
```

```{r}
ggplot(adni.df.no_dup, aes(x=site, y=age, color=sex, fill=sex)) + 
  geom_boxplot()
```

```{r}
summary(aov(age_days ~ site, data = adni.df.filt))
```

### Sex

```{r}
ggplot(adni.df.no_dup) +
  geom_bar(aes(x=site, fill=sex))
```

```{r}
ggplot(adni.df.no_dup) +
  geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..], x=site, fill=sex)) + 
  scale_y_continuous(labels = scales::percent)
```

### Diagnosis

```{r}
ggplot(adni.df.no_dup) +
  geom_bar(aes( y=..count../tapply(..count.., ..x.. ,sum)[..x..], x=site, fill=sex)) + 
  scale_y_continuous(labels = scales::percent) +
  facet_wrap(~dx)
```

```{r}
ggplot(adni.df.no_dup, aes(x=site, y=age, fill=dx, color=dx)) +
  geom_violin(scale="width", trim = FALSE, adjust=0.75)
```

```{r}
ggplot(adni.df.no_dup, aes(x=site, y=age, fill=dx, color=dx)) + 
  geom_boxplot() +
  facet_wrap(~sex, nrow=2)
```

Keep just CN, AD, and LMCI (same as longComBat paper)

```{r}
adni.df.no_dup %>%
  dplyr::filter(dx == "CN" | dx == "AD" | dx == "LMCI") %>%
ggplot() +
  geom_bar(aes(y=..count../tapply(..count.., ..x.. ,sum)[..x..], x=site, fill=dx)) + 
  scale_y_continuous(labels = scales::percent)

adni.df.no_dup %>%
  dplyr::filter(dx == "CN" | dx == "AD" | dx == "LMCI") %>%
ggplot() +
  geom_bar(aes(x=site, fill=dx))
```

