---
title: "hbm_paper_results"
output: html_document
date: '2023-11-12'
---

Rmd to show and get feedback on planned for results & figures for the combatLS paper. Currently thinking I'll have centile score results be the focus of the paper and keep z-scores for the supplement.

# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
if(!require('pacman')) {
  install.packages('pacman')
}
pacman::p_load(data.table, ggplot2, tidyverse, ggseg, ggsegExtra, paletteer, ggpubr, gridExtra, lemon, parallel, rstatix, lme4, interactions, ggrepel, ggrain)
#Sys.setenv("MC_CORES"=10L)
options("mc.cores")

source("./cubic_scripts/R_scripts/gamlss_helper_funs.R")
source("./cubic_scripts/R_scripts/ranked_welch_tests.R")
aseg_cerebrum <- readRDS(file="/Users/megardn/Desktop/BGD_Repos/ggseg_atlas/aseg_cerebrum_atlas.RDS")

data_path <- "/Users/megardn/Desktop/BGD_Repos/combat_biovar/data/lifespan"
```


# QC ComBat Outputs

csvs scp'd from cubic

Log-Scaled

```{r}
imp.sites_log.cf_cf.gam <- fread(file=paste0(data_path, "/lifespan-CN-imp-sites_log-cf_cf.gam_data.csv"))
sum(is.na(imp.sites_log.cf_cf.gam))
sum(imp.sites_log.cf_cf.gam < 0)
skimr::skim(imp.sites_log.cf_cf.gam$lh_Vol_posteriorcingulate)
min(imp.sites_log.cf_cf.gam$lh_Vol_posteriorcingulate)
```

```{r}
imp.sites_log.cf_cf.gamlss <- fread(file=paste0(data_path, "/lifespan-CN-imp-sites_log-cf_cf.gamlss_data.csv"))
sum(is.na(imp.sites_log.cf_cf.gamlss))
skimr::skim(imp.sites_log.cf_cf.gam$log_age)
skimr::skim(imp.sites_log.cf_cf.gam$sex)
skimr::skim(imp.sites_log.cf_cf.gam$sex.age)
skimr::skim(imp.sites_log.cf_cf.gam$fs_version)
skimr::skim(imp.sites_log.cf_cf.gam$Vol_total)
```


```{r}
data_path <- "/Users/megardn/Desktop/BGD_Repos/combat_biovar/derivatives"

pheno_list <- readRDS(file="cubic_scripts/R_scripts/pheno_list.rds")
vol_list_global <- readRDS(file="cubic_scripts/R_scripts/vol_list_global.rds")
vol_list_regions <- readRDS(file="cubic_scripts/R_scripts/Vol_list_regions.rds")
sa_list <- readRDS(file="cubic_scripts/R_scripts/SA_list.rds")
ct_list <- readRDS(file="cubic_scripts/R_scripts/CT_list.rds")

pheno_list.z <- paste0(pheno_list, ".z")
pheno_abs.diff.list <- paste0("abs.diff_", pheno_list)
z.pheno_abs.diff.list <- paste0("abs.diff_", pheno_list, ".z")

#also load raw data
ukb_cn_df <- fread("/Users/megardn/Desktop/BGD_Repos/combat_biovar/data/ukb_to_model/ukb_CN_data_simsites.csv")

#plotting info from dk atlas
dk.parc <- dk$data %>%
  as.data.frame() %>%
  na.omit() %>%
  dplyr::select(c(hemi, region, label)) %>%
  distinct()
```

